# Generated by Django 5.2 on 2025-05-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptablepet',
            name='image_url',
        ),
        migrations.AddField(
            model_name='adoptablepet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pets/'),
        ),
        migrations.AlterField(
            model_name='adoptablepet',
            name='age',
            field=models.IntegerField(),
        ),
    ]
