# Generated by Django 5.2 on 2025-05-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_remove_adoptablepet_image_url_adoptablepet_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptablepet',
            name='age',
        ),
        migrations.AddField(
            model_name='adoptablepet',
            name='age_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adoptablepet',
            name='age_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
