# Generated by Django 5.2 on 2025-05-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0003_remove_adoptablepet_age_adoptablepet_age_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptablepet',
            name='age_months',
        ),
        migrations.RemoveField(
            model_name='adoptablepet',
            name='age_years',
        ),
        migrations.AddField(
            model_name='adoptablepet',
            name='age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
