# Generated by Django 5.2 on 2025-05-18 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0004_remove_adoptablepet_age_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptablepet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='adoptablepet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='adoptable_pets/'),
        ),
        migrations.CreateModel(
            name='AdoptionInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='adoptions.adoptablepet')),
            ],
        ),
    ]
