# Generated by Django 5.2 on 2025-05-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('availability', models.CharField(max_length=200)),
                ('interests', models.TextField(help_text='E.g. Events, Fostering, Transport')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
